2024-10-01 22:36:06 | INFO    | __main__:stash:131 | run - {'image': '20231121', 'version': '0.10.1.post2', 'role': 'EpicPlayer', 'headless': True}
2024-10-01 22:36:16 | INFO    | __main__:claim_epic_games:97 | Try to flush cookie - {'task': 'claim_epic_games'}
2024-10-01 22:36:19 | INFO    | epic_games.agent:_login:237 | login-with-email - {'url': 'https://www.epicgames.com/id/login?lang=en-US&noHostRedirect=true&redirectUrl=https://store.epicgames.com/en-US/free-games&__cf_chl_rt_tk=YTWa97HB8JcC8noOsjlzz8TmNw3DU3c8da4ES9FZsWY-1727793379-0.0.1.1-6655'}
2024-10-01 22:36:49 | WARNING    | epic_games.agent:authorize:266 | 执行超时 - {'task': 'authorize', 'retry': 0}
2024-10-01 22:36:51 | INFO    | epic_games.agent:_login:237 | login-with-email - {'url': 'https://www.epicgames.com/id/login?lang=en-US&noHostRedirect=true&redirectUrl=https://store.epicgames.com/en-US/free-games&__cf_chl_rt_tk=B8eYsDP_JIIqbXdw1fsHC2m6DtGqky4bmieYv_ti.RQ-1727793411-0.0.1.1-7572'}
2024-10-01 22:37:21 | WARNING    | epic_games.agent:authorize:266 | 执行超时 - {'task': 'authorize', 'retry': 1}
2024-10-01 22:37:23 | INFO    | epic_games.agent:_login:237 | login-with-email - {'url': 'https://www.epicgames.com/id/login?lang=en-US&noHostRedirect=true&redirectUrl=https://store.epicgames.com/en-US/free-games&__cf_chl_rt_tk=bNvTbSDv87EkocrUkWHTyGZ08xYRCjYZXj81WZgtZ8Y-1727793443-0.0.1.1-7551'}
2024-10-01 22:37:53 | WARNING    | epic_games.agent:authorize:266 | 执行超时 - {'task': 'authorize', 'retry': 2}
2024-10-01 22:37:54 | ERROR    | __main__:run:158 | An error has been caught in function 'run', process 'MainProcess' (3729), thread 'MainThread' (139649293605760): - {}
Traceback (most recent call last):
  File "/home/runner/work/Epic_Auto/Epic_Auto/epic/src/claim.py", line 162, in <module>
    asyncio.run(run())
  File "/opt/hostedtoolcache/Python/3.10.15/x64/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/opt/hostedtoolcache/Python/3.10.15/x64/lib/python3.10/asyncio/base_events.py", line 636, in run_until_complete
    self.run_forever()
  File "/opt/hostedtoolcache/Python/3.10.15/x64/lib/python3.10/asyncio/base_events.py", line 603, in run_forever
    self._run_once()
  File "/opt/hostedtoolcache/Python/3.10.15/x64/lib/python3.10/asyncio/base_events.py", line 1909, in _run_once
    handle._run()
  File "/opt/hostedtoolcache/Python/3.10.15/x64/lib/python3.10/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
> File "/home/runner/work/Epic_Auto/Epic_Auto/epic/src/claim.py", line 158, in run
    await agent.stash()
  File "/home/runner/work/Epic_Auto/Epic_Auto/epic/src/claim.py", line 151, in stash
    await self.claim_epic_games(context)
  File "/home/runner/work/Epic_Auto/Epic_Auto/epic/src/claim.py", line 98, in claim_epic_games
    if await epic.authorize(page):
  File "/home/runner/work/Epic_Auto/Epic_Auto/epic/src/epic_games/agent.py", line 269, in authorize
    raise RuntimeError(f"Failed to flush token - agent={self.__class__.__name__}")
RuntimeError: Failed to flush token - agent=EpicGames
